### ISSUE TITLE
Question about spark sql customized parser

### ISSUE THREAD

**Issue by bithw1** [rtahboub/spark-sql-customized-parser#1]
Hi @rtahboub ,

Thanks very much for sharing how to customize spark sql parser. I am reading your blog at https://rtahboub.github.io/blog/2018/writing-customized-parser/，I have a few questions that are not clear.

It looks that  the steps you do the customization are(please correct me if I am wrong here):
1.  make a new copy of Spark SQL's SqlBase.g4 file
2. modify the g4 file by adding your own sql grammar
3. auto-generate the java files using ANTLR(parser.java, lexer.java, visitor.java etc),
4. add your own parser and astbuilder implementation(MyCatalystParser, MyAstBuilder)
5. Apply your extension to spark with ` extensions.injectParser((_, _) => MyCatalystSqlParser)`

With all the above steps in place and get the extended SparkSession, when you run a sql query,
```
1. select a from b(spark sql's own grammer)
2. select * from table1 knn join table2 using POINT(x2, y2) knnPred(POINT(x1, y1), 5)
(your extended grammar)
```

does it mean  spark will totally forget its own parser and use your extended parser  to parse these two queries? Or, spark will use its own parser for the first query and your parser for the second query 

And, what do you mean in your blog: `I also defined a new rule named spatialpredicated to get my KNN query through the parser`

And, when spark sql evolves with new sql grammar, it looks that the extended parser will have to do the above steps to  upgrade and apply for these new changes.

**Comment by rtahboub** [comment]
In this program, Spark will use the injected parser: https://github.com/rtahboub/spark-sql-customized-parser/blob/master/src/main/scala/example/FrontEnd.scala#L17

For the second question, I meant modifying the grammar file to support new syntax: https://github.com/rtahboub/spark-sql-customized-parser/blob/master/src/main/scala/org/apache/spark/sql/catalyst/parser/SqlBase.g4#L534

Best,
Ruby

**Comment by bithw1** [comment]
Thanks @rtahboub for the answer!

**Comment by gabry-lab** [comment]
Excellent project and blog. Actually, we can create our own grammar file, it's too heavy to use a copy from SqlBase.g4
